package com.inventory_forcasting.models;

public enum EventType {
    USER_LOGIN, USER_LOGOUT, USER_REGISTRATION,
    USER_GET_ALL,
    SALE_RECORDED, PRODUCT_CREATED, ORDER_RECEIVED,
    API_REQUEST,
    HEALTH_CHECK, SALE_RECORDED_FAILED, PRODUCT_GET,
    PRODUCT_GET_FAILED,
    PRODUCT_GET_ALL, ORDER_GENERATED, ORDER_GENERATED_ERROR,
    ORDER_GENERATING,
    ORDER_GET_ALL, ORDER_RECEIVED_ERROR,
    FORECAST_GENERATING, FORECAST_GET_ALL,
    LLM_PARSE, FORECAST_GET_BY_DATE_RANGE
}
